website1:
  url: http://www.google.pl
  keyword: search
  frequency: '10s'

website2:
  url: http://www.chomikuj.pl
  keyword: param pam pam
  frequency: '1m'

website3:
  url: https://www.facebook.com
  keyword: cmg
  frequency: '3s'

website4:
  url: https://www.localhost.tralalala
  keyword: can't \touch \\me
  frequency: '10s'
