website1:
  url: http://www.google.pl
  keyword: search
  frequency: '10s'

website2:
  url: http://www.chomikuj.pl
  keyword: param
  frequency: '1m'

website3:
  url: https://www.facebook.com
  keyword: foo
  frequency: '3s'

website4:
  url: https://www.localhost.com
  keyword: can't
  frequency: '10s'

website5:
  url: http://www.plus.google.com
  keyword: Google
  frequency: '1h'

website6:
  url: https://stackoverflow.com/
  keyword: "developers, "
  frequency: '1s'

website7:
  url: https://www.facebook.com
  keyword: cmg
  frequency: '3s'

website8:
  url: https://reddit.com
  keyword: karma
  frequency: '10s'

website9:
  url: http://127.0.0.1:5000
  keyword: LAST CHECK
  frequency: '1m'


website10:
  url: https://twitter.com/
  keyword: Dołącz do rozmowy
  frequency: '2m'
